### ISSUE TITLE
Tried multiple IP addresses in OpenCTI and, in every case I get 0 entities even though there are Indicators and Observables seen in OpenCTI

### ISSUE THREAD

**Issue by smclinden** [amr-cossi/opencti-maltego#1]
Currently running OpenCTI 3.3.2 on Ubuntu 18.04 and Maltego on OS X 10.15.5. Python 3.8.

**Comment by amr-cossi** [comment]
Hi,

I can't reproduce your issue.
I have never tested the compatibility of Maltego-TRX with Python3.8 and I don't have any OS-X environment to test but if other local transforms are running it should be something else.

Do you have an error while running a transform (in debug mode) ?
Which transform are you running ?
From which entity type ?
Do you use heritage between Maltego-STIX2 entities and generic Maltego entities ?

On my side, adding an IPv4 and running the transform Observable to Indicators works fine.

**Comment by smclinden** [comment]
IPv4 addresses. I was trying to reproduce the behavior in the video.

I search on an IP address and it returns an Indicator and an Observable in OpenCTI. But when I run the transform in Maltego I get nothing.

**Comment by amr-cossi** [comment]
A new version compatible with OpenCTI v4 has been pre-released.
Please re-open a bug if this is still an issue after the upgrade.
