### ISSUE TITLE
Dependency Issues with stix2, pycti, and maltego-stix2

### ISSUE THREAD

**Issue by DaltonBrownOfficial** [amr-cossi/opencti-maltego#12]
In requirements.txt, stix2 has version 2.1.0 but pycti version 5.2.4 requires stix2 version 3.0.1. I cannot change stix2 to version 3.0.1 however because maltego-stix2 requires stix2 version 2.1.0. I believe the solution is change the requirements for the maltego-stix2 package to require stix2 version 2.1.0 or above (stix2>=2.1.0).

**Comment by netmg** [comment]
I've run into the same problem as @DaltonBrownOfficial  - were you able to resolve the conflicting requirements?  On a whim, I looked for an updated maltego-stix2 option but it's still not available:

ERROR: Could not find a version that satisfies the requirement maltego-stix2>=3.0.0 (from versions: 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1, 2.1.1)
