### ISSUE TITLE
Need help to add the property "kill_chain_phases" in the transform "OpenCTI: Attack Pattern to Details"

### ISSUE THREAD

**Issue by JeromeSRT** [amr-cossi/opencti-maltego#2]
Hello all,
I can't add the property "kill_chain_phases" in the transform "OpenCTI: Attack Pattern to Details" on the AttackPattern in Maltego.
I added "entity.addProperty(fieldName="kill_chain_phases", value=opencti_entity["killChainPhasesIds"])" in the code source of the addAttackPattern function in the addEntities.py file.
When Maltego runs the "OpenCTI: Attack Pattern to Details" transform, there is the following error :
Traceback (most recent call last):
  File "/Users/Jerome/Applications/OpenCTI/opencti-maltego/src/OpenCTI.py", line 94, in <module>
    entity = searchAndAddEntity(
  File "/Users/Jerome/Applications/OpenCTI/opencti-maltego/src/addEntities.py", line 737, in searchAndAddEntity
    maltego_entity = addAttackPattern(transform, opencti_entity)
  File "/Users/Jerome/Applications/OpenCTI/opencti-maltego/src/addEntities.py", line 317, in addAttackPattern
    fieldName="kill_chain_phases", value=opencti_entity["killChainPhasesIds"]
KeyError: 'killChainPhasesIds'

Could you explain me how to resolve this error ?

Thanks, Jerome.

**Comment by amr-cossi** [comment]
I think opencti_entity only has a field named "killChainPhases" containing a list. You would need to iterate over this list to add id(s) or phase_name(s).
