### ISSUE TITLE
Update Plugin to Support OpenCTI 4.x

### ISSUE THREAD

**Issue by tellerj** [amr-cossi/opencti-maltego#3]
Request to update this plugin/connector to be compatible with the latest major release of OpenCTI. Thanks!

**Comment by amr-cossi** [comment]
We are working on it, as well as better STIX2.1 base entities.

**Comment by amr-cossi** [comment]
Handled here : https://github.com/amr-cossi/opencti-maltego/tree/feature/opencti-v4
